var git = require('simple-git/promise')
var personalSite = require('personal-site')
var fs = require('fs-extra');
var blogGit=git()
var ghPagesGit=git()

Promise.all([(fs.existsSync('src/blog')?Promise.resolve(true):blogGit.clone('git@github.com:AGrzes/AGrzes.github.io.git', 'src/blog', ['--branch', 'blog', '--single-branch']))
.then(()=>blogGit.cwd('src/blog'))
.then(()=>blogGit.pull())
.then(()=>blogGit.reset('hard')),
(fs.existsSync('dst')?Promise.resolve(true):ghPagesGit.clone('git@github.com:AGrzes/AGrzes.github.io.git', 'dst', ['--single-branch']))
.then(()=>ghPagesGit.cwd('dst'))
.then(()=>ghPagesGit.pull())
.then(()=>ghPagesGit.reset('hard'))])
.then(()=>personalSite(__dirname+'/src',__dirname+'/tmp',null,'http://site.abramczykg.pl/'))
.then(()=>fs.removeSync('dst/blog'))
.then(()=>fs.renameSync('tmp/blog','dst/blog'))
.then(()=>ghPagesGit.add('.'))
.then(()=>ghPagesGit.commit('Updating blog'))
.then(()=>ghPagesGit.push())
